GET https://gorest.co.in/public/v2/users

###

GET https://gorest.co.in/public/v2/users/7601195

###

POST https://gorest.co.in/public/v2/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer babc358ca5c037f0693b5bb17e9e8436db1b21a682c2c92ef1ad61f1c4a4819b

{
  "name": "sekar1",
  "email": "sekar1@sekar1.com",
  "gender": "female",
  "status": "inactive"
}

###

PUT https://gorest.co.in/public/v2/users/7600214
Content-Type: application/json
Authorization: Bearer babc358ca5c037f0693b5bb17e9e8436db1b21a682c2c92ef1ad61f1c4a4819b

{
  "name": "sekar2",
  "email": "sekar2@sekar2.com",
  "gender": "male",
  "status": "active"
}

###

DELETE https://gorest.co.in/public/v2/users/7600214
Content-Type: application/json
Authorization: Bearer babc358ca5c037f0693b5bb17e9e8436db1b21a682c2c92ef1ad61f1c4a4819b
